# Generated by Django 4.2.3 on 2023-07-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenity",
            name="category",
        ),
        migrations.AddField(
            model_name="room",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
