# Generated by Django 4.2.3 on 2023-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perk",
            old_name="detail",
            new_name="details",
        ),
        migrations.AddField(
            model_name="perk",
            name="explanation",
            field=models.TextField(default=True),
        ),
    ]
